### ISSUE TITLE
vue2项目中使用报错

### ISSUE THREAD

**Issue by dodu2014** [wanglin2/VideoTimeLine#19]
![image](https://github.com/wanglin2/VideoTimeLine/assets/15245544/c58e8f01-7f87-4c34-b8d4-ce11583a8e89)

看demo中使用的less，和less-loader，我也添加了这个依赖，还是报错，求解

**Comment by zwdgit** [comment]
出现同样的问题

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/VideoTimeLine/assets/17272433/5d2e58e5-51b0-4de2-b119-fd6b34e49ce1)
一般是版本太高了，可以降版本试试
