### ISSUE TITLE
连接的时间间隔，绘制出来有间隙

### ISSUE THREAD

**Issue by landOfsun** [wanglin2/VideoTimeLine#2]
如果第一段的结束时间和第二段的开始时间一致，绘制出来中间存在空隙，希望可以优化一下下呢。
ex:
timeSegments: [
        {
          name: '时间段1',
          beginTime: new Date('2021-01-13 10:00:00').getTime(),
          endTime: new Date('2021-01-14 23:00:00').getTime(),
          color: '#FA3239',
          startRatio: 0.65,
          endRatio: 0.9
        },
         {
          name: '时间段2',
          beginTime: new Date('2021-01-14 23:00:00').getTime(),
          endTime: new Date('2021-01-14 23:30:00').getTime(),
          color: '#FA3239',
          startRatio: 0.65,
          endRatio: 0.9
        },
]

**Comment by wanglin2** [comment]
已修复~
