### ISSUE TITLE
如何有1个可以跟随时间进度的刻度线

### ISSUE THREAD

**Issue by dodu2014** [wanglin2/VideoTimeLine#20]
你好，首先感谢作者的开源，让学习到很多，给作者点赞。
在我的项目中利用到了该组件，用来完成监控视频回放功能中的时间轴。如下图：

![image](https://github.com/wanglin2/VideoTimeLine/assets/15245544/53f77162-23c1-4909-b9ea-5ea3cd272346)

在使用过程中，想更好的展现进度，如题，怎样可以有1个跟随时间进度的刻度线，并且在支持缩放和拖拽的情况下，也实时随播放进度而移动呢（也就是作者说到的重绘）。

**Comment by dodu2014** [comment]
已自行实现

![image](https://github.com/wanglin2/VideoTimeLine/assets/15245544/90244abc-0058-402e-86c9-e1542eda5191)

**Comment by SnowBeatRain** [comment]
方便分享下吗
