### ISSUE TITLE
希望在月视图 显示已经选中的时间段

### ISSUE THREAD

**Issue by viki719632** [wanglin2/VideoTimeLine#3]
![image](https://user-images.githubusercontent.com/20202439/216012608-4e8521bd-8a94-429a-96e4-6d27fd600f02.png)
![image](https://user-images.githubusercontent.com/20202439/216012639-aded3178-d36e-45aa-82d2-a9bf068e023d.png)
图一，有显示选中的时段
图二没有
另外，希望图一中的时间可以宽一点 目前看起来太密了

**Comment by wanglin2** [comment]
月视图时间段没绘制出来是因为时间段太短了，几个小时计算出来才1像素不到，根本绘制不出来

**Comment by viki719632** [comment]
是的 只要显示1像素就行 让用户知道自己有选中过

**Comment by wanglin2** [comment]
改了一下，升级到0.1.7试试，宽度不足1px会显示1px，另外时间太密的问题可以参考：https://github.com/wanglin2/VideoTimeLine#%E5%B1%9E%E6%80%A7%E8%AF%A6%E8%A7%A31-1-customshowtime%E7%9A%84%E7%94%A8%E6%B3%95

**Comment by viki719632** [comment]
![image](https://user-images.githubusercontent.com/20202439/216225598-0fda6012-1ac0-47a7-a20b-9acd64dd87c4.png)
感谢
宽度显示1px的问题已经好了，小时太密也解决了
但是日视图下 时期间距还是有点小

**Comment by viki719632** [comment]
如上图，
日视图下 时期间距还是可以调大一点吗

**Comment by wanglin2** [comment]
通过customShowTime属性处理不了么
