### ISSUE TITLE
选时间段的时候 建议选开始时间的时候 加个竖线

### ISSUE THREAD

**Issue by viki719632** [wanglin2/VideoTimeLine#4]
现在点击时间段开始时间的时候 是没有任何显示的 建议加个竖线 让用户清楚自己有点击过

**Comment by wanglin2** [comment]
没看懂。。。

**Comment by viki719632** [comment]
当我选择时间段的时候，需要点两次，第一次是开始时间，第二次是结束时间
选中第一次的时候 ui上是没有反馈的

**Comment by wanglin2** [comment]
截个图看看

**Comment by viki719632** [comment]
![image](https://user-images.githubusercontent.com/20202439/216266946-45805ce9-36d3-4c0b-8a4b-38263236a671.png)
比如说，我现在点击了时间轴，已经选好了开始时间
开始时间在组件是没有标记的

**Comment by wanglin2** [comment]
修改了一下，现在时间段数据可以只传一个beginTime，更新到0.1.8试试

**Comment by viki719632** [comment]
只有beginTime的时候，可以支持设置不同颜色吗
不同颜色可以区分 这是分辨率缩小看起来只有一条  还是只有beginTime看起来只有一条

**Comment by wanglin2** [comment]
只有beginTime的时候，可以支持不同颜色，只有beginTime会绘制一根1px的线
