### ISSUE TITLE
希望加个单日模式

### ISSUE THREAD

**Issue by viki719632** [wanglin2/VideoTimeLine#6]
希望增加只显示当天的 从00:00:00到23:59:59的

**Comment by wanglin2** [comment]
把`enableZoom`和`enableDrag`设为`false`，然后把初始时间设置为当天的`12:00:00`，显示的就是显示当天的 从00:00:00到23:59:59的了

**Comment by viki719632** [comment]
![1675396799384](https://user-images.githubusercontent.com/20202439/216509564-b1761c57-b4e7-4b23-8870-4c4621af252b.jpg)
样式是需要调整的，两侧的时间轴被遮住了一点

**Comment by viki719632** [comment]
![image](https://user-images.githubusercontent.com/20202439/216509657-c097667b-5546-447e-a985-fbef1ececb53.png)
鼠标经过的时候 会显示年月日，时分秒
单日模式是不需要的

**Comment by viki719632** [comment]
![image](https://user-images.githubusercontent.com/20202439/216509919-3b80eff6-6696-4493-b074-320f6c12ddb0.png)
这里显示了下一天的日期

**Comment by wanglin2** [comment]
给你提供了一种解决方案，可以参考：https://github.com/wanglin2/VideoTimeLine#%E5%B1%9E%E6%80%A7%E8%AF%A6%E8%A7%A31-2--extendzoom%E7%9A%84%E7%94%A8%E6%B3%95

**Comment by wanglin2** [comment]
demo中的最后一个https://wanglin2.github.io/VideoTimeLine/

**Comment by wanglin2** [comment]
需要升级到0.1.9

**Comment by viki719632** [comment]
0.1.9 有升级到Npm吗
我这边npm 升级报错了

**Comment by wanglin2** [comment]
再试试

**Comment by viki719632** [comment]
那timeSegments要如何设置
`[
        {
          name: '时间段1',
          beginTime:$dayjs().format('YYYY-MM-DD 12:00:00').valueOf(),
          endTime: dayjs().format('YYYY-MM-DD 13:00:00').valueOf(),
          color: '#FA3239',
          startRatio: 0.65,
          endRatio: 0.9
        }
]`
这么设置无效

**Comment by viki719632** [comment]
可以的  完美

**Comment by 995713047** [comment]
初始只展示当天时间按照上述配置没有问题 ，但是一旦传入其他日期，初始时间为第一个视频播放的时间的时候 时间刻度尺就会展示其他天数的时间了，请问怎么固定就展示 当天24小时的时间刻度

**Comment by 995713047** [comment]
初始化只显示当天时间按照上述配置没有问题，但是一旦传入其他日期，初始时间为第一个视频播放的时间的时候，时间刻度尺就会显示其他天数的时间了，请问怎么固定就显示当天24小时的时间
