### ISSUE TITLE
点击timeSegments 需要获取当前时间

### ISSUE THREAD

**Issue by viki719632** [wanglin2/VideoTimeLine#7]
目前timeSegments 点击的时候 回调的参数中只有 点击的时间段
需要获取点击的时间

**Comment by viki719632** [comment]
还要加个标记在点击的当前时间， 也就是要加个竖线，这个竖线是可以修改位置的

**Comment by wanglin2** [comment]
timeSegments 点击的时间已增加~

**Comment by wanglin2** [comment]
timeSegments 点击的时间已增加~
